"use client";

import { useState } from "react";
import { ChevronDown, ChevronUp, Sparkles, Calculator } from "lucide-react";
import { Badge } from "@/components/ui/badge";

export interface InsightCardProps {
  headline: string;
  body: string;
  citedFigures: { label: string; value: number }[];
  severity: "info" | "positive" | "warning" | "critical";
  source: "ai" | "cache" | "deterministic";
}

const severityTone = {
  info: "neutral",
  positive: "success",
  warning: "warning",
  critical: "danger",
} as const;

export function InsightCard({ headline, body, citedFigures, severity, source }: InsightCardProps) {
  const [open, setOpen] = useState(false);
  const isAi = source === "ai" || source === "cache";

  return (
    <div className="rounded-xl border border-border bg-surface p-4 space-y-2">
      <div className="flex items-center justify-between gap-3">
        <div className="flex items-center gap-1.5 text-xs text-ink-muted">
          {isAi ? <Sparkles className="h-3.5 w-3.5 text-accent" /> : <Calculator className="h-3.5 w-3.5" />}
          {isAi ? "AI insight" : "Computed insight"}
        </div>
        <Badge tone={severityTone[severity]}>{severity}</Badge>
      </div>
      <p className="font-display text-base font-semibold text-ink">{headline}</p>
      <p className="text-sm text-ink-muted leading-relaxed">{body}</p>
      <button
        onClick={() => setOpen((o) => !o)}
        className="text-xs text-accent hover:text-accent-hover font-medium inline-flex items-center gap-1"
      >
        Why? {open ? <ChevronUp className="h-3 w-3" /> : <ChevronDown className="h-3 w-3" />}
      </button>
      {open && (
        <div className="text-xs text-ink-muted bg-surface-muted rounded-lg p-3 space-y-1.5">
          <p className="font-medium text-ink">
            {isAi
              ? "Generated by AI, grounded only in the figures below — it never does its own math."
              : "Computed directly from your data (AI is unavailable or disabled)."}
          </p>
          {citedFigures.length > 0 ? (
            <ul className="space-y-0.5">
              {citedFigures.map((f, i) => (
                <li key={i} className="flex justify-between gap-3">
                  <span>{f.label}</span>
                  <span className="font-mono text-ink">{f.value.toLocaleString("en-IN")}</span>
                </li>
              ))}
            </ul>
          ) : (
            <p>No individual figures were cited for this insight.</p>
          )}
        </div>
      )}
    </div>
  );
}
